<#
.SYNOPSIS
  Set up a Windows 11 host for ntdrive in one run.

.DESCRIPTION
  Checks vmrun.exe, kd.exe and kdnet.exe, installs the Python environment with uv, puts the
  ntdrive, ntdrive-mcp and ntdrived commands on PATH (uv tool install, editable, so they run this
  checkout), then runs `ntdrive setup` for each VM you want (pick it from the VMware library,
  enter the guest account and the passwords, which go to User environment variables and never
  into a file), runs `ntdrive kd setup-host` for every configured VM (net, the default: repairs
  the host firewall for kd.exe through one UAC prompt. serial: adds the named-pipe COM port to
  the vmx while the VM is off) and ends with `ntdrive verify`, which proves every VM end to end
  (SSH login, debugger attach, break in, resume) and prints ALL SET, or the first thing to fix.
  -Verify runs only that last part, for example after setup-guest.cmd ran in a guest later.

  Nothing here needs an elevated PowerShell. Run it again to add a VM. -FirewallOnly is the
  manual route for the KDNET firewall rules and is the one thing that needs an Administrator
  PowerShell.

.EXAMPLE
  scripts\setup-host.cmd
  Interactive: lists the VMs VMware knows, asks for the account and passwords. The .cmd launcher
  runs this script whatever the PowerShell execution policy says.

.EXAMPLE
  scripts\setup-host.cmd -Vmx D:\VMs\win11\win11.vmx -Name win11 -User dev
  One VM with the answers given up front. Only the passwords are asked.

.EXAMPLE
  scripts\setup-host.cmd -Verify
  Only the end-to-end check, whichever of the two scripts ran last.

.EXAMPLE
  scripts\setup-host.cmd -FirewallOnly
  Administrator PowerShell: remove the kd.exe Block rules and recreate the Allow rule, nothing else.
#>

[CmdletBinding()]
param(
  [string]$Vmrun = "C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe",
  [string]$Kd = "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\kd.exe",
  [string]$Vmx,
  [string]$Name,
  [string]$User,
  [string]$Transport,
  [switch]$InlineSecrets,
  [switch]$SkipVms,
  [switch]$Verify,
  [switch]$FirewallOnly
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

function Invoke-NtDrive([string[]]$Arguments) {
  # --no-sync: the environment was synced above, and a re-sync would rewrite ntdrive-mcp.exe,
  # which fails while an MCP client keeps it open.
  & uv run --no-sync ntdrive @Arguments
  if ($LASTEXITCODE -ne 0) { throw "ntdrive $($Arguments -join ' ') failed (exit $LASTEXITCODE)" }
}

if ($FirewallOnly) {
  Write-Host "== firewall for kd.exe (KDNET UDP inbound), manual route"
  $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
  if (-not $isAdmin) { throw "-FirewallOnly needs an Administrator PowerShell. 'ntdrive kd setup-host <vm>' does the same through a UAC prompt." }
  # The repair script is generated by the package, so the tool route and this route agree.
  Push-Location $root
  try {
    $script = (& uv run --no-sync python -c "import sys; from ntdrive.kd.firewall import fix_script; sys.stdout.write(fix_script(sys.argv[1]))" $Kd) -join "`n"
    if ($LASTEXITCODE -ne 0 -or -not $script) { throw "could not generate the repair script (run uv sync first)" }
  } finally {
    Pop-Location
  }
  Invoke-Expression $script
  Write-Host "  Block rules for $Kd removed, Allow rule 'ntdrive kd.exe KDNET' recreated"
  Write-Host "done"
  exit 0
}

Write-Host "== binaries"
foreach ($p in @($Vmrun, $Kd, (Join-Path (Split-Path $Kd) "kdnet.exe"))) {
  if (Test-Path $p) { Write-Host "ok      $p" } else { Write-Warning "missing $p" }
}

Write-Host "== python environment"
if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
  throw "uv is not installed. See https://docs.astral.sh/uv/"
}
if ($Verify) {
  Push-Location $root
  try {
    # A failed sync (for example the MCP client holding ntdrive-mcp.exe) must not stop the check:
    # the environment from the last full run is enough. No stderr redirection here, because with
    # ErrorActionPreference Stop that turns uv's progress lines into a terminating error.
    uv sync | Out-Null
    & uv run --no-sync ntdrive verify
    exit $LASTEXITCODE
  } finally {
    Pop-Location
  }
}

Push-Location $root
try {
  uv sync
  if ($LASTEXITCODE -ne 0) { throw "uv sync failed" }
  if (Test-Path (Join-Path $root ".git")) { uv run pre-commit install | Out-Null }

  Write-Host "== commands on PATH: ntdrive, ntdrive-mcp, ntdrived"
  $installed = @(uv tool list 2>$null) -match '^ntdrive v'
  if ($installed) {
    # An editable install already follows this checkout. Reinstalling would rewrite the
    # launchers, which fails while an MCP client (Claude Code) keeps ntdrive-mcp.exe open.
    Write-Host "  already installed ($installed). After a dependency change run, with Claude Code closed:"
    Write-Host "  uv tool install --editable --reinstall ."
  } else {
    uv tool install --editable .
    if ($LASTEXITCODE -ne 0) { Write-Warning "uv tool install failed, the commands below still work through uv run" }
    $toolBin = (uv tool dir --bin).Trim()
    if (-not (($env:Path -split ";") -contains $toolBin)) {
      Write-Warning "$toolBin is not on PATH. Run 'uv tool update-shell', then open a new terminal."
    }
  }

  if (-not $SkipVms) {
    Write-Host "== VMs (vms.yaml goes to %LOCALAPPDATA%\ntdrive, passwords to User environment variables)"
    $first = @("setup")
    if ($Vmx) { $first += @("--vmx", $Vmx) }
    if ($Name) { $first += @("--name", $Name) }
    if ($User) { $first += @("--user", $User) }
    if ($Transport) { $first += @("--transport", $Transport) }
    $again = @("setup")
    if ($InlineSecrets) { $first += "--inline-secrets"; $again += "--inline-secrets" }
    Invoke-NtDrive $first
    while (-not $Vmx -and (Read-Host "Add another VM? [y/N]") -match "^[Yy]") {
      Invoke-NtDrive $again
    }
  } else {
    Write-Host "== daemon"
    Invoke-NtDrive @("daemon", "restart")
  }

  Write-Host "== kd transport per VM (net: firewall, one UAC prompt. serial: pipe in the vmx, VM off)"
  $vms = ((& uv run --no-sync ntdrive --json vm list) | ConvertFrom-Json).vms
  foreach ($vm in $vms) {
    if ($vm.kd.transport -eq "serial" -and $vm.power -ne "off") {
      Write-Warning "$($vm.name): power it off, then run: ntdrive kd setup-host $($vm.name)"
      continue
    }
    Write-Host "-- $($vm.name) ($($vm.kd.transport))"
    & uv run --no-sync ntdrive kd setup-host $vm.name
    if ($LASTEXITCODE -ne 0) { Write-Warning "$($vm.name): kd setup-host did not finish, see above" }
  }

  Write-Host "== verify (config, power, SSH login, firewall, then attach, break in, resume)"
  & uv run --no-sync ntdrive verify
  $ready = ($LASTEXITCODE -eq 0)
} finally {
  Pop-Location
}

if (-not $ready) {
  Write-Host ""
  Write-Host "Not everything answered yet. In each guest run setup-guest.cmd (copy it with setup-guest.ps1: OpenSSH plus"
  Write-Host "KDNET, add -Serial for the serial transport). Then on the host: scripts\setup-host.cmd -Verify"
  Write-Host "(or ntdrive verify). It reboots the guest when the debugger needs it and ends with ALL SET."
}
